# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QuhjkdRYoH-QbrZctejx25MbUtE0Kgp
"""

matrix = '2' + '   ' + '3' + '   ' + '5' + '\n' + '7' + '   ' + '11' + '  ' + '13' + '\n' + '17' + '  ' + '19' + '  ' + '23'
print(matrix)